#!/usr/bin/ansible-playbook
#
# Deploy Cluster Operator to a development cluster.
#
# Wraps the main deploy-playbook.yaml and adds additional performs additional
# devel specific tasks.
---

# Perform a normal deployment:
- import_playbook: deploy-playbook.yaml

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    # Namespace to deploy CO to:
    cluster_operator_namespace: "openshift-cluster-operator"
  tasks:

  - import_role:
      name: kubectl-ansible

  - name: create/update playbook mock deployment
    kubectl_apply:
      namespace: "{{ cluster_operator_namespace }}"
      src: "{{ playbook_dir }}/../examples/deploy-playbook-mock.yaml"

  - debug: msg="Deployment complete, you may need to push images to the registry or start a build before the Cluster Operator will deploy. (see README.md)"
