#!/usr/bin/ansible-playbook
#
# Deploy Cluster Operator to a development cluster.
#
# Wraps the main deploy-playbook.yaml and adds additional performs additional
# devel specific tasks.
---

# Perform a normal deployment:
- import_playbook: deploy-playbook.yaml

- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    # Namespace to deploy CO to:
    cluster_operator_namespace: "openshift-cluster-operator"
  tasks:

  - import_role:
      name: kubectl-ansible

  - name: process cluster versions template
    oc_process:
      template_file: "{{ playbook_dir }}/../examples/cluster-versions-template.yaml"
    register: cluster_versions_reg

  - name: wait for our apiserver and create/update cluster versions
    kubectl_apply:
      definition: "{{ cluster_versions_reg.result | to_json }}"
    register: result
    # Wait up to 2 minutes for our apiserver to be accepting our types:
    until: result.failed == false
    retries: 24
    delay: 5

  - name: create/update playbook mock deployment
    kubectl_apply:
      namespace: "{{ cluster_operator_namespace }}"
      src: "{{ playbook_dir }}/../examples/deploy-playbook-mock.yaml"
